<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPulvnzp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPulvnzp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPulvnzp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPulvnzp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPulvnzp\appProdProjectContainer([
    'container.build_hash' => 'Pulvnzp',
    'container.build_id' => '840c2496',
    'container.build_time' => 1720609929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPulvnzp');
