<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXzikc6g\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXzikc6g/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXzikc6g.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXzikc6g\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXzikc6g\appDevDebugProjectContainer([
    'container.build_hash' => 'Xzikc6g',
    'container.build_id' => '98e51742',
    'container.build_time' => 1722089719,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXzikc6g');
